openapi: "3.1.0"
info:
  version: 1.1.0
  title: Yosif Petrov website API
  summary: >
    Contains all API endpoints used by the actual application
    to allow users to interact with it
  termsOfService: http://swagger.io/terms/
  contact:
    name: Christo Yovev
    url: https://github.com/chyovev/ypetrov
    email: yovev@xroads-bg.com
tags:
  - API

paths:
  /api/contact:
    post:
      summary: Send a contact message
      operationId: send_contact_message
      tags:
        - API
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ContactMessage'
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Your message has been successfully created!"
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Unauthorized'
        429:
          $ref: '#/components/responses/TooManyRequests'

  /api/comments/{id}:
    post:
      summary: Add a comment to a resource
      operationId: comment_resource
      tags:
        - API
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Comment'
      parameters:
        - $ref: '#/components/parameters/path/id'
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Your comment has been successfully created!"
                  html:
                    type: string
                    example: <div>New comment's HTML</div>
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        429:
          $ref: '#/components/responses/TooManyRequests'

  /api/likes/{id}:
    post:
      summary: Like a likable resource
      operationId: like_resource
      tags:
        - API
      parameters:
        - $ref: '#/components/parameters/path/id'
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Resource successfully liked!"
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          allOf:
            - $ref: '#/components/responses/Conflict'
            - description: Resource already liked
        429:
          $ref: '#/components/responses/TooManyRequests'
    delete:
      summary: Revoke a like from a likable resource
      operationId: revoke_like_from_resource
      tags:
        - API
      parameters:
        - $ref: '#/components/parameters/path/id'
      responses:
        204:
          description: Response contains no content
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          allOf:
            - $ref: '#/components/responses/Conflict'
            - description: Resource should be liked first
        429:
          $ref: '#/components/responses/TooManyRequests'

components:
  parameters:
    path:
      id:
        in: path
        name: id
        description: Resource id
        required: true

  schemas:
    ContactMessage:
      type: object
      required:
        - name
        - message
      properties:
        name:
          type: string
          maximum: 255
          example: John Smith
        email:
          type: string
          format: email
          maxmium: 255
        message:
          type: string
          maximum: 65535
          example: Hello, world!

    Comment:
      type: object
      required:
        - name
        - message
      properties:
        name:
          type: string
          maximum: 255
          example: John Smith
        message:
          type: string
          maximum: 65535
          example: Hello, world!

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: The request could not be completed
        errors:
          type: object
          properties:
            key1:
              type: array
              items:
                type: string
                example: The key1 field is required
            key2:
              type: array
              items:
                type: string
                example: The key2 field format is invalid

  responses:
    BadRequest:
      description: Bad Request (input validation failure)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: User has no access (potentially banned)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Conflict:
      description: Request is correct, but it cannot be finished due to a conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    TooManyRequests:
      description: Too Many Requests in a short period of time
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'